[Base]
text = {color6.hex}
subtext = {color5.hex}
sidebar-text = {color4.hex}
main = {surface.hex}
sidebar = {color1.hex}
player = {color0.hex}
card = {color2.hex}
shadow = {source_color.hex}

; [Material You]
; text               = ${ON_SURFACE}
; subtext            = ${ON_SURFACE}
; main               = ${SURFACE}
; sidebar            = ${BACKGROUND}
; player             = ${BACKGROUND}
; card               = ${SURFACE}
; shadow             = 000000
; selected-row       = ${PRIMARY}
; button             = ${PRIMARY}
; button-active      = ${PRIMARY}
; button-disabled    = 535353
; tab-active         = ${PRIMARY}
; notification       = ${PRIMARY}
; notification-error = ${ERROR}
; misc               = FFFFFF
